[devservers]
devvm ansible_host=192.168.56.10 ansible_user=vagrant ansible_ssh_private_key_file=/home/olesya/Desktop/devops-course/devops-ai-assistant/10_Implementation/01_vm/.vagrant/machines/default/virtualbox/private_key
